package io.github.datagenerator.domain.providers.transform;

import io.github.datagenerator.domain.annotation.Provider;
import io.github.datagenerator.domain.annotation.ProviderArg;
import io.github.datagenerator.domain.annotation.ProviderCtor;
import io.github.datagenerator.domain.core.ValueProvider;

/**
 * Converti une valeur en String
 */
@Provider(
        name = "AsString",
        description = "Wrap a value generated by a provider to a string",
        examples = {
                "AsString(Integer()) => \"5\"",
                "AsString(Double(0, 10)) => \"6.19938784958678\"",
                "AsString(Boolean()) => \"true\""
        },
        returns = String.class
)
public class AsString<I> extends TransformerProvider<I, String> {

    @ProviderCtor
    public AsString(
            @ProviderArg(description = "Provider of any type", examples = "IntIncrement()")
            ValueProvider<I> provider
    ) {
        super(provider);
    }

    @Override
    protected String map(I input) {
        if (input == null) {
            return null;
        }
        return String.valueOf(input);
    }
}
