# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Create release

on:
  workflow_dispatch:
    inputs:
        releaseVersion:
          description: 'Release version'     
          required: true
        nextVersion:
          description: 'Next version'     
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_GH_ACTIONS }}

    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github 
        settings-path: ${{ github.workspace }}

    - name: Update pom.xml with release version
      run: mvn versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
    
    - name: Configure git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github-actions"
    
    - name: Commit & push pom.xml
      run: |
        git add pom.xml
        git commit -m "Release version ${{ github.event.inputs.releaseVersion }}"
        git push
        
    - name: Crete & push tag
      run: |
        git tag "v${{ github.event.inputs.releaseVersion }}"
        git push --tags
        
    - name: Update pom.xml version with next version
      run: mvn versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}
      
    - name: Commit & push pom.xml
      run: |
        git add pom.xml
        git commit -m "Next version ${{ github.event.inputs.nextVersion }}"
        git push
