name: Publish release

on:
  push:
    tags:
      - '*'
     
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload assets on the release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./data-generator-api/target/data-generator-api-[0-9]*.[0-9]*.*[0-9]?(-SNAPSHOT)-runner.jar
          ./data-generator-core/target/data-generator-core-[0-9]*.[0-9]*.*[0-9]?(-SNAPSHOT).jar
          ./data-generator-cli/target/data-generator-cli-[0-9]*.[0-9]*.*[0-9]?(-SNAPSHOT).jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
